version: "3"

networks:
  fraude-network:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - fraude-network

  db:
    image: mysql:5.7.33
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - "./docker/db/fraude-mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=efraude190
    networks:
      - fraude-network
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  fraude-network:

volumes:
  fraude-mysql:

